name: Continuous Integration and Development

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2 
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore
        
      - name: Publish with dotnet
        run: dotnet publish --configuration Release -o './Publish'
      - name: file transfer to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 103.108.146.179
          port: 1433
          username: hannan
          password: datavanced123!
          exclude: |
            /.git*
            /.git*/
            /supportboard/**
          local-dir: ./PassionCareFTP
